### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by teesloane** [teesloane/moonview#2]
MoonView aims for simplicity. Features and functionality have been split into Core, and Release Candidate components. Please note that the `#Ideas` list is tentative; I don't want to get carried away with trying to make something too complex and forget the main goal. 
# Core Functionality
- [x] File I/O 
- [x] Change backgrounds / Listen to Music / Key Sounds / Type Faces
- [x] Turn off asset (background, audio, key sounds etc)

---
# Features 1.0
- [x] basic menu (toggleable, shows currently selected asset)
- [x] Volume control for music / field recordings?
- [ ] User preferences window
  - [ ] Font size
  - [ ] Font color for "dark font" and "light font"
  - [ ] text editor Width
  - [ ] auto save (+ toggleable, on by default?)
  - [ ] accessibility related font visibility
- [ ] splash screen on startup / caching.
- [ ] accept more file formats (.md, .rtf)
## Prep 1.0 :
- [ ] Write music
- [ ] Collect all field recordings
- [ ] Get ball rolling on branding / logo. 

---

**Comment by teesloane** [comment]
# 0.02 Beta Release:
- [x] clicking on a button de-focuses the text area.
- [x] currently selected button (`sounds`, `type` etc) should be highlighted
- [x] refactor getElementById's to a separate file.
- [x] replace key sounds with field recordings

**Comment by teesloane** [comment]
# 0.03 Beta Release
- [x] refactor js / scss
- [x] clicking anywhere in the text editor should close the menu.
- [x] create an audio volume menu
- [x] add new field recordings

**Comment by teesloane** [comment]
# 0.04 Beta Todo:
- [x] allow for [tiled](http://subtlepatterns.com/) background images
- [x] new images!
- [ ] programatically change font colour based on darkness of background
